### PR TITLE
Add ESLint

### LINKED ISSUE #12: Add linting

### PR DESCRIPTION
**Pull request by rramphal**
Resolves #12

### CODE REVIEW

**Comment by Whoaa512** [comment]
Perhaps standardize on using [Prettier](https://prettier.io/) while you're at it?

**Comment by rramphal** [comment]
Created #18!

**Comment by zcaceres** [comment]
Great stuff!

Love ESLint. I want to be sure we don't go too crazy with the draconian AirBnB style rules so I may disable a few of the idiosyncratic ones as they're encountered. Otherwise it's a great base

**Comment by Whoaa512** [comment]
@rramphal I don't love it's _style_ completely, but it completely kills any time-wasting stylistic conversation about JS code which I do love.

**Pull request merged**
